embedding_base_url: "https://ws-yi9oakgdflk8zstn.cn-beijing.maas.aliyuncs.com/compatible-mode/v1"
embedding_model: "qwen3.7-text-embedding"
embedding_batch_size: 20

chat_base_url: "https://ws-yi9oakgdflk8zstn.cn-beijing.maas.aliyuncs.com/compatible-mode/v1"
chat_model: "qwen3.7-flash"